server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ewm
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
stats.server.url=http://localhost:9090